// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onSystemOnChange();

float cloudGForce;
int bpm;
bool systemOn;

void initProperties(){

  ArduinoCloud.addProperty(cloudGForce, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(bpm, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(systemOn, READWRITE, ON_CHANGE, onSystemOnChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
